services:
  proxy:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./__deploy__/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./__deploy__/nginx/lxd.conf:/etc/nginx/templates/default.conf.template
      - ./__deploy__/nginx/certificates/nginx.crt:/etc/nginx/crts/nginx.crt
      - ./__deploy__/nginx/certificates/nginx.key:/etc/nginx/crts/nginx.key
    environment:
      - LXD_SERVER_URL=https://192.168.29.102:8443
    ports:
      - 8080:80

  db:
    image: mysql:oraclelinux9
    container_name: mysql-1
    volumes:
      - ./__deploy__/mysql/my.cnf:/etc/my.cnf
      - ./__deploy__/mysql/data:/var/lib/mysql
      - ./__deploy__/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
      - 33060:33060

  cache:
    image: redis:alpine3.23
    container_name: redis
    volumes:
      - ./__deploy__/redis/data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    ports:
      - 6379:6379

  # Monitoring
  scraper:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.16.0}
    container_name: alloy
    ports:
      - 12345:12345
      - 4318:4318
    volumes:
      - ./__deploy__/loki/config.alloy:/etc/alloy/config.alloy
      - ./logs:/temp/logs
    command: run --server.http.listen-addr=0.0.0.0:12345 --stability.level=experimental  --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - logs_collector

  logs_collector:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.6.10}
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./__deploy__/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-13.0.1}
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 8001:3000/tcp
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        EOF
        /run.sh
